-- Seleccionar BD
USE `apis-uade-simpsons`;

-- Eliminar la tabla USERS si ya existe
DROP TABLE IF EXISTS USERS;

-- Crear la tabla USERS con la estructura proporcionada
CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_USERNAME VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255),
    USER_LASTNAME VARCHAR(255),
    USER_ADMINISTRATOR BOOLEAN,
    USER_EMAIL VARCHAR(255) UNIQUE,
    USER_PASSWORD_HASH VARCHAR(255)
);