-- Seleccionar BD
USE `apis-uade-simpsons`;

-- Eliminar la tabla USERS si ya existe
DROP TABLE IF EXISTS PRODUCT_ORDERED;

CREATE TABLE PRODUCT_ORDERED (
    PRODUCT_ORDERED_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ORDERED_ORDER_ID BIGINT NOT NULL,
    PRODUCT_ORDERED_NAME VARCHAR(255),
    PRODUCT_ORDERED_PRICE FLOAT,
    PRODUCT_ORDERED_QUANTITY INT,
    FOREIGN KEY (PRODUCT_ORDERED_ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT chk_quantity CHECK (PRODUCT_ORDERED_QUANTITY > 0),
    CONSTRAINT chk_price CHECK (PRODUCT_ORDERED_PRICE > 0)
);