-- Seleccionar BD
USE `apis-uade-simpsons`;

-- Eliminar la tabla USERS si ya existe
DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    ORDER_DATE_TIME DATETIME NOT NULL,
    ORDER_TOTAL FLOAT NOT NULL,
    ORDER_CARD_NUMBER BIGINT NOT NULL,
    ORDER_ADDRESS VARCHAR(255) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);